name: "Build Desktop"

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm64 & Intel
            args: "--target universal-apple-darwin"
          - platform: "ubuntu-22.04" # for Linux
            args: ""
          - platform: "windows-latest" # for Windows
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos-latest
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: install Linux dependencies
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: build DocuMind Backend
        run: ./gradlew clean build -x test

      - name: prepare Backend Artifact
        shell: bash
        run: |
          mkdir -p frontend/src-tauri/binaries
          cp app/core/build/libs/*ocu?ind-*.jar frontend/src-tauri/binaries/DocuMind.jar

      - name: install Frontend dependencies
        run: cd frontend && npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # the action automatically replaces this with the app version
          releaseName: "DocuMind v__VERSION__"
          releaseBody: "See the assets below for the latest installers."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          projectPath: frontend
